name: Kale Stedman
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfef6'
    - '#0e040c'
    - '#312d2d'
    - '#6d6d6b'
    - '#deb99f'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.7015422019176185
purpose: []
